# Generated by Django 3.2.16 on 2023-06-28 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_at',)},
        ),
    ]
