# Generated by Django 3.2.16 on 2023-06-29 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-views', '-likes', 'created_at')},
        ),
    ]
